[borderlands]
maxFile = 9
maxRank = 10
# Non-promoting pieces.
customPiece1 = c:KmNmAmD
customPiece2 = g:KmNmAmD
# Unpromoted pieces.
customPiece3 = a:RmFcpR
customPiece4 = s:BmWcpB
customPiece5 = h:NmB3
customPiece6 = e:ADmR3
customPiece7 = m:FmN
customPiece8 = f:WmAmD
customPiece9 = w:fWfceFifmnD
customPiece10 = l:KNAD
# Promoted pieces.
customPiece11 = b:RFcpR
customPiece12 = d:BWcpB
customPiece13 = i:NFmWmB3
customPiece14 = j:ADWmFmR3
customPiece15 = k:KmN
customPiece16 = n:KmAmD
customPiece17 = o:NADmQ3
customPiece18 = p:KNAD
promotedPieceType = a:b s:d h:i e:j m:k f:n w:o l:p
mandatoryPiecePromotion = true
startFen = a1hs1sh1a/1ce1l1ec1/fwgw1wgwf/w1w1w1w1w/9/9/W1W1W1W1W/FWGW1WGWF/1CE1L1EC1/A1HS1SH1A[MMmm] w - - 0 1
mobilityRegionWhiteCustomPiece1 = *1 *2 *3 *8 *9 *10 a* e* i*
mobilityRegionBlackCustomPiece1 = *1 *2 *3 *8 *9 *10 a* e* i*
mobilityRegionWhiteCustomPiece10 = *1 *2 *3 *4 *5 d7 f7 e9
mobilityRegionBlackCustomPiece10 = *6 *7 *8 *9 *10 d4 f4 e2
flagPiece = *
flagPieceCount = 4
flagRegion = b2 h2 b9 h9
flagMove = true
pieceDrops = true
capturesToHand = false
whiteDropRegion = *6 *7
blackDropRegion = *4 *5
promotionRegionWhite = *8 *9 *10
promotionRegionBlack = *1 *2 *3
doubleStepRegionWhite = *3
doubleStepRegionBlack = *8
nMoveRule = 100
perpetualCheckIllegal = true
moveRepetitionIllegal = true
extinctionValue = loss
extinctionPseudoRoyal = false
extinctionPieceTypes = c
extinctionPieceCount = 0
